### PR TITLE
I rewrote the thing in ASTRO

### PR DESCRIPTION
**Pull request by sharon-xa**
Easier and cleaner code and it is still fast cuz astro uses server side rendering.
it's easier to customize the thing now, just open the constants file and start editing.
it's not just easier but more customizable too, now you can change all colors and the transition duration.
Screenshot_20230913_092116

### CODE REVIEW

**Comment by imreyesjorge** [comment]
I’ll give this a look, thanks for your PR!

I built the project around the idea of not using any external tooling to make it easir for anyone to use it (even not devs). What's your posture about using astro, given that this will increase a little bit the level of tooling necessary to run this project?

**Comment by sharon-xa** [comment]
To change things like the colors or the cards you can edit the constants.ts file, only one file with few lines to edit
and then you can run the file ./build.sh that I created to automate and abstract the process of building and moving the folder that contain the index.html
the script will build the project and then rename the dist folder to startpage and then move startpage into ~/Documents

This script works on linux only
If you approve This pull request, I'll make sure that the script works on windows too
And we can make a Readme file to explain to people what to do, I don't think it's hard, Specially if we wrote a good Readme and made sure the scripts are working for everybody

**Comment by imreyesjorge** [comment]
It seems like a great idea, I'll try to review the PR over the week and determine what to do 🙏🏻

**Comment by imreyesjorge** [comment]
Hey @sharonye0, sorry for the late response. 

Everything looks great, love what you did with the cards width taking more space if possible.

The only two thing that I can leave a comment on are:

- Cards accessibility navigation is kinda broken. The border color isn’t showing properly while tab-navigating.
- The circle container for the icons is a little bit off (more like an ellipsis).

Beside that everything it’s great and easy to customize!

After thinking a bit, first I thought about merging this into another branch, say `main-astro` for people who prefer to use astro. But that would make the maintenance difficult. So maybe the best path is for you to host that repo!

Feel free to rename and change the project as you like, and if you decide to host it, you can contact me to put your fork on the README.md of this project.

**Pull request closed without merging**
